name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Determine Version and Create Tag
        run: |
          version=$(date +'%Y%m%d%H%M%S')
          echo "Generated version: $version"  # For debugging purposes
          git tag $version
          git push origin $version
